### ISSUE TITLE
include all journal details on change

### ISSUE THREAD

**Issue by hi-ko** [zulip/zulip-redmine-plugin#13]
The plugin sends a message in zulip but if the ticket has only changes in the details (no comment) you can't see the changes. 
On the REST-API I would add include=attachments,journals but I don't know how to extend the zulip_hooks.rb to send changes as seen in the ticket journal.
e.g. 
`Status changed from Work in Progress to Feedback` or
`Checklist item todo 2 set to Done` or
`Assignee set to Peter Lustig`

**Comment by felipebatista** [comment]
hello @hi-ko could you please try using the plugin's new released **2.0** version?

let me know what fields are missing on changing message

**Comment by felipebatista** [comment]
I am closing this issue for inactivity

**Comment by hi-ko** [comment]
Sorry for the late response. I tried to upgrade to 2.0.1 on redmine 3.4.3.stable by running 

    bundle exec rake redmine:plugins NAME=redmine_zulip RAILS_ENV=production

Do you still support redmine 3.4?

I get 

````
rake aborted!
SyntaxError: ./plugins/redmine_zulip/lib/redmine_zulip/issue_patch.rb:156: syntax error, unexpected '.'
        status: status&.name
                        ^
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/current/plugins/redmine_zulip/lib/redmine_zulip.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/current/plugins/redmine_zulip/init.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/current/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine/current/lib/redmine/plugin.rb:146:in `each'
/opt/redmine/current/lib/redmine/plugin.rb:146:in `load'
/opt/redmine/current/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/redmine/current/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/redmine/current/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
````

**Comment by felipebatista** [comment]
@hi-ko thank you for the detailed feedback

I have just released a **2.0.2** version, could you please to upgrade to this one?

**Comment by hi-ko** [comment]
@felipebatista thank your very much for your fast reaction!
I was able to install and migrate the 2.0.2 plugin without errors.
Unfortunately, now I don't get any notifications in zulip. Global plugin config is still set and in the project i checked all options:
![2019-09-02-12_28_44](https://user-images.githubusercontent.com/5754182/64108523-48f2f980-cd7d-11e9-8d8d-d91c78df0196.png)

**Comment by felipebatista** [comment]
@hi-ko is the stream named `test` already created on your Zulip instance? do you have anything on your Redmine that may indicate any problem?

**Comment by hi-ko** [comment]
@felipebatista the stream exists and worked already for this project before upgrading the plugin.
In the redmine debug log I don't see any error but also no debug for executing the http call to zulip.
I already removed plugin_redmine_zulip settings in the db since I've seen configs which should only apply to the old version and set config again in admin but still don't get any message.

On the zulip server I see:

    2019-09-02 11:11:17.080 WARN [django.request] Not Found: /api/api/v1/messages

we run

    "zulip_version": "2.0.4",

**Comment by hi-ko** [comment]
sorry - while reading my own message I found the problem:
the url config has changed. I removed /api from the config and now it's working.

Thanks a lot for the update.

last question: version 3 is for redmine 4.x only?

**Comment by felipebatista** [comment]
@hi-ko go to your plugin settings and remove the `/api` suffix from your Zulip URL, like the following:

![zulip-redmine-settings-url](https://user-images.githubusercontent.com/213949/64111162-45af3c00-cd84-11e9-95b7-dac17c86e946.jpg)

**Comment by felipebatista** [comment]
@hi-ko yes, version **3** is compatible only with Redmine 4.x :)
